DMP_HOST: "localhost:3000"
DMP_EMAIL_FROM: "address@example.com"
DMP_SMTP_ADDRESS: "localhost"
DMP_SMTP_PORT: 25

DMP_ERR_EMAIL_PREFIX: "[DMPonline4 ERROR] "
DMP_ERR_EMAIL_SENDER_ADDRESS: "\"No-reply\" <noreply@dcc.ac.uk>"
DMP_ERR_EMAIL_EXCEPTION_RECIPIENTS: "[\"dmponline@dcc.ac.uk\"]"

DMP_CONTACT_US_EMAIL_FROM: "dmponline@dcc.ac.uk"
DMP_CONTACT_US_EMAIL_TO: "dmponline@dcc.ac.uk"

DEVISE_EMAIL_FROM: "info@dcc.ac.uk"
DEVISE_PEPPER: "de451fa8d44af2c286d922f753d1b10fd23b99c10747143d9ba118988b9fa9601fea66bfe31266ffc6a331dc7331c71ebe845af8abcdb84c24b42b8063386530"

SHIBBOLETH_LOGIN: "https://localhost/Shibboleth.sso/Login"
SHIBBOLETH_ENABLED: true
WICKED_PDF_EXE: "/usr/local/bin/wkhtmltopdf"
